import 'dart:async';
import 'dart:convert';

import 'package:injectable/injectable.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../../auth/data/graphql_client.dart';
import '../models/question_list.dart';

/// Source of truth for the user's **custom** question lists.
///
/// The product requirement is "the UI reacts instantly, the data lives in the
/// backend database", so every mutation is applied to the in-memory list first
/// (and published on [changes] straight away), then sent to
/// `saobracaj_backend`. If the call fails the optimistic change is rolled back
/// and the error is rethrown for the Bloc to surface.
///
/// The lists are also cached in shared preferences, so a cold start renders the
/// chips before (or without) a network round trip. Automatic lists are not
/// stored here — they are derived from the local answer history by
/// `QuestionListsBloc`.
@lazySingleton
class QuestionListsRepository {
  QuestionListsRepository(this._client);

  final GraphqlClient _client;

  static const _cacheKey = 'question_lists_cache';

  static const _fields = 'id name color questionIds';

  final StreamController<List<QuestionList>> _controller =
      StreamController<List<QuestionList>>.broadcast();

  List<QuestionList> _lists = const [];

  Future<SharedPreferences> get _prefs => SharedPreferences.getInstance();

  /// The current custom lists, replayed to each new listener followed by every
  /// subsequent change.
  Stream<List<QuestionList>> get changes async* {
    yield _lists;
    yield* _controller.stream;
  }

  /// The latest known custom lists (synchronous read).
  List<QuestionList> get lists => _lists;

  /// Publish the cached lists, then refresh from the backend. Both steps are
  /// best-effort: an offline start keeps whatever was cached.
  Future<void> bootstrap() async {
    await _loadCache();
    await refresh();
  }

  /// Pull the lists from the backend and replace the local copy. Failures are
  /// swallowed — the cached lists stay in effect.
  Future<void> refresh() async {
    try {
      final data = await _client.run(
        'query MyQuestionLists { myQuestionLists { $_fields } }',
        authenticated: true,
      );
      final raw = data['myQuestionLists'];
      if (raw is! List) return;
      _publish(raw.map(_parse).toList(), cache: true);
    } catch (_) {
      // Offline / signed out — keep the cached lists.
    }
  }

  /// Forget everything when the session ends: custom lists belong to a user.
  Future<void> onLoggedOut() async {
    _publish(const [], cache: false);
    (await _prefs).remove(_cacheKey);
  }

  /// Create a list, optionally pre-filled with [questionIds] (the "create a list
  /// from the question screen" flow). The id is generated by the caller so the
  /// new list can be rendered — and ticked — before the backend answers.
  Future<void> create(QuestionList list) async {
    final previous = _lists;
    _publish([..._lists, list], cache: true);
    await _mutate(
      previous,
      '''
        mutation CreateQuestionList(\$id: ID!, \$name: String!, \$color: Int!, \$questionIds: [Int!]) {
          createQuestionList(id: \$id, name: \$name, color: \$color, questionIds: \$questionIds) { $_fields }
        }
      ''',
      {
        'id': list.id,
        'name': list.name,
        'color': list.color,
        'questionIds': list.questionIds,
      },
    );
  }

  /// Rename and/or recolour a list.
  Future<void> update(String id, {String? name, int? color}) async {
    final previous = _lists;
    _publish(
      _lists
          .map(
            (l) => l.id == id
                ? l.copyWith(name: name ?? l.name, color: color ?? l.color)
                : l,
          )
          .toList(),
      cache: true,
    );
    await _mutate(
      previous,
      '''
        mutation UpdateQuestionList(\$id: ID!, \$name: String, \$color: Int) {
          updateQuestionList(id: \$id, name: \$name, color: \$color) { $_fields }
        }
      ''',
      {'id': id, 'name': name, 'color': color},
    );
  }

  /// Delete a list. The backend keeps the row and only flags it `deleted`.
  Future<void> delete(String id) async {
    final previous = _lists;
    _publish(_lists.where((l) => l.id != id).toList(), cache: true);
    await _mutate(
      previous,
      r'mutation DeleteQuestionList($id: ID!) { deleteQuestionList(id: $id) }',
      {'id': id},
    );
  }

  /// Add or remove one question — the checkbox in the question screen's "add to
  /// list" menu.
  Future<void> setQuestionIncluded(
    String listId,
    int questionId,
    bool included,
  ) async {
    final previous = _lists;
    _publish(
      _lists.map((l) {
        if (l.id != listId) return l;
        final ids = [...l.questionIds]..remove(questionId);
        if (included) ids.add(questionId);
        return l.copyWith(questionIds: ids);
      }).toList(),
      cache: true,
    );
    await _mutate(
      previous,
      '''
        mutation SetQuestionInList(\$listId: ID!, \$questionId: Int!, \$included: Boolean!) {
          setQuestionInList(listId: \$listId, questionId: \$questionId, included: \$included) { $_fields }
        }
      ''',
      {'listId': listId, 'questionId': questionId, 'included': included},
    );
  }

  /// Replace a list's contents with exactly [questionIds], in that order — used
  /// for drag-and-drop reordering and for removing a question from the list
  /// screen.
  Future<void> setQuestions(String listId, List<int> questionIds) async {
    final previous = _lists;
    _publish(
      _lists
          .map(
            (l) => l.id == listId ? l.copyWith(questionIds: questionIds) : l,
          )
          .toList(),
      cache: true,
    );
    await _mutate(
      previous,
      '''
        mutation SetQuestionListQuestions(\$listId: ID!, \$questionIds: [Int!]!) {
          setQuestionListQuestions(listId: \$listId, questionIds: \$questionIds) { $_fields }
        }
      ''',
      {'listId': listId, 'questionIds': questionIds},
    );
  }

  /// Run a mutation behind an already-applied optimistic change; on failure the
  /// [previous] snapshot is restored before the error reaches the caller.
  Future<void> _mutate(
    List<QuestionList> previous,
    String mutation,
    Map<String, dynamic> variables,
  ) async {
    try {
      await _client.run(mutation, variables: variables, authenticated: true);
    } catch (_) {
      _publish(previous, cache: true);
      rethrow;
    }
  }

  QuestionList _parse(dynamic raw) =>
      QuestionList.fromJson((raw as Map).cast<String, dynamic>());

  void _publish(List<QuestionList> lists, {required bool cache}) {
    _lists = List.unmodifiable(lists);
    _controller.add(_lists);
    if (cache) unawaited(_saveCache());
  }

  Future<void> _loadCache() async {
    try {
      final raw = (await _prefs).getString(_cacheKey);
      if (raw == null) return;
      final decoded = jsonDecode(raw);
      if (decoded is! List) return;
      _publish(decoded.map(_parse).toList(), cache: false);
    } catch (_) {
      // A corrupt cache is not worth crashing over.
    }
  }

  Future<void> _saveCache() async {
    try {
      final payload = jsonEncode(_lists.map((l) => l.toJson()).toList());
      (await _prefs).setString(_cacheKey, payload);
    } catch (_) {
      // Best-effort cache.
    }
  }
}
